project_id = "vhxglsvxwwpmoqjabfmj"

[functions.send-invitation-email]
verify_jwt = false

[functions.send-ownership-notification]
verify_jwt = false

[functions.shared-media-sign]
verify_jwt = false
