project_id = "vhxglsvxwwpmoqjabfmj"

[functions.send-invitation-email]
verify_jwt = true

[functions.send-ownership-notification]
verify_jwt = false

[functions.shared-media-sign]
verify_jwt = false

[functions.expire-stale-connections]
verify_jwt = false

[functions.backend-proxy]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false
